import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#f3f3f3',
  '--slot4-page-text': '#111111',
  '--slot4-panel-bg': '#fafafa',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#666666',
  '--slot4-soft-muted-text': '#999999',
  '--slot4-accent': '#e05a4a',
  '--slot4-accent-fill': '#e05a4a',
  '--slot4-accent-soft': '#ffdede',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#040405',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#e7e7e7',
  '--slot4-cream': '#fbfbfb',
  '--slot4-warm': '#f4f4f4',
  '--slot4-lavender': '#151515',
  '--slot4-gray': '#fafafa',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#f3f3f3',
  '--editable-page-text': '#111111',
  '--editable-container': '1500px',
  '--editable-border': '#e6e6e6',
  '--editable-nav-bg': '#040405',
  '--editable-nav-text': '#ffffff',
  '--editable-nav-active': '#e05a4a',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#e05a4a',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#040405',
  '--editable-footer-text': '#ffffff',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_1px_0_rgba(17,17,17,0.10)]',
  shadowStrong: 'shadow-[0_24px_70px_rgba(0,0,0,0.14)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.04),rgba(0,0,0,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-5 sm:px-6 lg:px-8',
    sectionY: 'py-16 sm:py-20 lg:py-24 xl:py-[8.75rem]',
  },
  layout: {
    safeGrid: 'grid gap-5 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[260px] shrink-0 snap-start sm:w-[320px]',
  },
  type: {
    eyebrow: 'editable-label text-xs font-semibold uppercase tracking-[0.18em] text-[var(--slot4-accent)]',
    heroTitle: 'editable-display text-[4rem] font-medium leading-[0.88] sm:text-[7rem] lg:text-[9.9vw]',
    sectionTitle: 'editable-display text-4xl font-medium leading-[0.96] sm:text-5xl lg:text-[4.375rem]',
    body: 'text-base leading-8 sm:text-[1.12rem]',
    emphasis: 'editable-display text-2xl font-medium leading-tight sm:text-4xl',
  },
  surface: {
    card: `rounded-md border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-md border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-md ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: 'inline-flex items-center justify-center gap-2 rounded bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-semibold capitalize text-[var(--slot4-on-accent)] transition duration-300 hover:-translate-y-1 hover:brightness-95',
    secondary: 'inline-flex items-center justify-center gap-2 rounded border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-semibold capitalize text-[var(--slot4-page-text)] transition duration-300 hover:-translate-y-1 hover:border-[var(--slot4-page-text)]',
    accent: 'inline-flex items-center justify-center gap-2 rounded bg-[var(--slot4-page-text)] px-6 py-3 text-sm font-semibold capitalize text-[var(--slot4-page-bg)] transition duration-300 hover:-translate-y-1',
    ghost: 'inline-flex items-center justify-center gap-2 rounded border border-current/20 px-6 py-3 text-sm font-semibold capitalize transition duration-300 hover:-translate-y-1 hover:bg-current/5',
  },
  badge: {
    pill: 'editable-label inline-flex items-center gap-2 rounded-full border border-current/15 px-4 py-2 text-xs font-medium uppercase tracking-[0.16em]',
    accentPill: 'editable-label inline-flex items-center gap-2 rounded-full bg-[var(--slot4-accent-soft)] px-4 py-2 text-xs font-medium uppercase tracking-[0.16em] text-[var(--slot4-accent)]',
  },
  media: {
    frame: `relative overflow-hidden rounded-md ${editablePalette.mediaBg}`,
    frameFull: `relative overflow-hidden rounded-[2.563rem] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[16/10]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-[0.313rem] hover:shadow-[0_18px_45px_rgba(0,0,0,0.12)]',
    fade: 'transition duration-300 hover:opacity-80',
    zoom: 'transition duration-500 group-hover:scale-[1.06]',
  },
} as const

export const aiLayoutRules = [
  'Map all visual decisions through editableRootStyle and editableDesignContract before touching page components.',
  'Use Funnel Display for oversized title moments, Mona Sans for body/UI, and Chivo Mono for mini labels.',
  'Keep task labels display-only; route keys and data calls must remain unchanged.',
  'Use sharp-soft cards, flat borders, coral accent cues, and large media rhythms from the Venture FZ reference.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
